spring:
  application:
    name: escape-room-backend
  datasource:
    url: "jdbc:postgresql://${database.host}:${database.port}/capitole"
    username: capitole
    password: capitole
    driver-class-name: "org.postgresql.Driver"
  flyway:
    enabled: false

discount:
  category-rules:
    HOME_AND_KITCHEN: 25.0
    ELECTRONICS: 15.0